services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=OpenApi.Ordering;Username=tmikava;Password=Npottwyctd12
    networks:
      - app-network

networks:
  app-network:
    driver: bridge



